## PyTorch 소개 및 설치
- 음...

### PyTorch 소개
- PyTorch란
    - PyTorch는 Python 기반의 오픈 소스 머신러닝 라이브러리로, 연구 및 개발을 위해 널리 사용됨
    - Facebook AI Research (FAIR)에서 개발되었으며, 동적 연산 그래프와 유연한 설계로 유명함

- 다른 딥러닝 프레임워크
    - TensorFlow, Keras와 비교
    - 동적 연산 그래프 vs 정적 연산 그래프
    - PyTorch의 장단점

### PyTorch 기본 문법
- Tensor 개념 및 기본 연산
    - Tensor란
    - Numpy와 Tensor의 비교

- Tensor 생성 및 조작
    - Tensor 생성 방법
        1. 직접 생성
        2. Numpy 배열로부터 생성
        3. 그외 초기화 방법(zeros, ones, random 등)

In [1]:
# 모듈 불러오기
import torch
import numpy as np

In [2]:
# 직접 생성
x = torch.tensor([1, 2, 3, 4])
x

tensor([1, 2, 3, 4])

In [3]:
# Numpy 배열로부터 생성
np_array = np.array([5, 6, 7, 8])
y = torch.from_numpy(np_array)
y

tensor([5, 6, 7, 8], dtype=torch.int32)

In [4]:
# 초기화
z = torch.zeros((2, 3))
z

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [5]:
w = torch.ones((2, 3))
w

tensor([[1., 1., 1.],
        [1., 1., 1.]])

In [6]:
r = torch.rand((2, 3))
r

tensor([[0.2537, 0.5867, 0.0882],
        [0.8651, 0.0954, 0.1670]])

- Tensor의 기본 연산
    - 기본 수학 연산 (덧셈, 뺄셈, 곱셈, 나눗셈)
    - 브로드캐스팅 및 Element-wise 연산

In [7]:
a = torch.tensor([1.0, 2.0])
b = torch.tensor([3.0, 4.0])

# 덧셈
c = a + b
c

tensor([4., 6.])

In [8]:
# 곱셈
d = a * b
d

tensor([3., 8.])

In [10]:
# 브로드캐스팅 - 작은 텐서를 자동으로 확장하여 크기가 맞는 텐서와 연산을 수행하는 기능
e = torch.tensor([[1.0], [2.0], [3.0]])
f = torch.tensor([1.0, 2.0])
g = e + f
g

tensor([[2., 3.],
        [3., 4.],
        [4., 5.]])

In [15]:
h = torch.tensor([1, 2, 3])  # 크기 (3,)
i = torch.tensor([[10], [20], [30]])  # 크기 (3, 1)

result = h + i  # 브로드캐스팅 적용
result

tensor([[11, 12, 13],
        [21, 22, 23],
        [31, 32, 33]])

In [17]:
h.size()

torch.Size([3])

In [18]:
i.size()

torch.Size([3, 1])

In [19]:
result.size()

torch.Size([3, 3])

- Tensor 조작
    - Tensor의 크기 변경 (Reshaping)
    - Indexing 및 Slicing
    - Joining (Concatenation) 및 Splitting

In [20]:
# Reshaping
a = torch.arange(6)
a

tensor([0, 1, 2, 3, 4, 5])

In [21]:
b = a.reshape((2, 3))
b

tensor([[0, 1, 2],
        [3, 4, 5]])

In [23]:
# Indexing
x = torch.tensor([[1, 2, 3], [4, 5, 6]])
x

tensor([[1, 2, 3],
        [4, 5, 6]])

In [26]:
x[0, 0]  # 첫 번째 행, 첫 번째 열 요소

tensor(1)

In [25]:
# Slicing
x[:, 1]    # 모든 행의 두 번째 열

tensor([2, 5])

In [27]:
# Concatenation
y = torch.tensor([[7, 8, 9], [10, 11, 12]])
z = torch.cat((x, y), dim=0)  # 행 방향으로 결합
z

tensor([[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9],
        [10, 11, 12]])

In [28]:
z = torch.cat((x, y), dim=1)  # 열 방향으로 결합
z

tensor([[ 1,  2,  3,  7,  8,  9],
        [ 4,  5,  6, 10, 11, 12]])

In [29]:
# Splitting
split_x = torch.split(x, 1, dim=0)  # 행 단위로 분할
split_x

(tensor([[1, 2, 3]]), tensor([[4, 5, 6]]))

- 기초 연산
    - 기본 수학 연산
    - 덧셈, 뺄셈, 곱셈, 나눗셈
    - Broadcast 및 Element-wise 연산

In [30]:
a = torch.tensor([1, 2, 3])
b = torch.tensor([4, 5, 6])

In [31]:
# 덧셈
c = a + b
c

tensor([5, 7, 9])

In [32]:
# 뺄셈
d = a - b
d

tensor([-3, -3, -3])

In [33]:
# 곱셈
e = a * b
e

tensor([ 4, 10, 18])

In [34]:
# 나눗셈
f = a / b
f

tensor([0.2500, 0.4000, 0.5000])

In [36]:
# Broadcasting
a = torch.tensor([[1], [2], [3]])
b = torch.tensor([4, 5, 6])
c = a + b
c

tensor([[5, 6, 7],
        [6, 7, 8],
        [7, 8, 9]])

In [37]:
# Element-wise 연산
d = torch.tensor([1, 2, 3])
e = torch.tensor([4, 5, 6])
f = d * e
f

tensor([ 4, 10, 18])

- 통계 및 수학 함수
    - 기본 통계 함수
    - 평균, 표준 편차, 최대값, 최소값
    - 수학 함수(제곱, 제곱근, 지수, 로그)

In [39]:
x = torch.tensor([1.0, 2.0, 3.0, 4.0, 5.0])

mean_x = torch.mean(x)
mean_x

tensor(3.)

In [40]:
std_x = torch.std(x)
std_x

tensor(1.5811)

In [42]:
max_x = torch.max(x)
max_x

tensor(5.)

In [43]:
min_x = torch.min(x)
min_x

tensor(1.)

In [44]:
# 제곱
x = torch.tensor([1.0, 2.0, 3.0])

square_x = torch.square(x)
square_x

tensor([1., 4., 9.])

In [45]:
# 제곱근
sqrt_x = torch.sqrt(x)
sqrt_x

tensor([1.0000, 1.4142, 1.7321])

In [46]:
# 지수
exp_x = torch.exp(x)
exp_x

tensor([ 2.7183,  7.3891, 20.0855])

In [48]:
# 로그
log_x = torch.log(x)
log_x

tensor([0.0000, 0.6931, 1.0986])

: 