## 자동미분

### 내용
1. 자동 미분
    - Autograd란
        - 자동 미분(Automatic Differentiation)은 기계 학습 모델의 학습 과정에서 기울기(Gradient)를 자동으로 계산하는 기능
        - PyTorch의 Autograd는 역전파(Backpropagation) 알고리즘을 사용하여 연산 그래프를 통해 기울기를 계산
    - 자동미분의 원리
        - 연산 그래프
        - 기울기 계산을 위한 그래프의 역전파

2. 기본 개념
    - Tensor의 requires_grad 속성
        - requires_grad=True로 설정된 Tensor는 연산 기록을 추적하여 기울기 계산 가능
    - 기울기 계산 - 기본 연산을 통해 생성된 Tensor의 기울기 계산

In [2]:
import torch

In [2]:
x = torch.tensor([1.0, 2.0, 3.0], requires_grad=True)
x

tensor([1., 2., 3.], requires_grad=True)

In [4]:
y = x + 2
z = y * y * 2

result = z.mean()  # 평균

In [5]:
result.backward()  # 기울기 계산

x.grad

tensor([4.0000, 5.3333, 6.6667])

- https://dataanalysiswithpython.tistory.com/entry/PyTorch-6?category=1223154 
    - 3번부터 계속

3. Autograd를 활용한 기울기 계산
    - $ f(x) = x ^ 2 + 3 x + 2 $

In [6]:
x = torch.tensor(2.0, requires_grad=True)

y = x**2 + 3*x + 2
y.backward()

x.grad  # x에서의 기울기 출력

tensor(7.)

- 다중 변수를 사용하는 함수의 기울기 계산
    - $ f(x, y) = 3 x ^ 2 + 2 x y + y ^ 2 $

In [9]:
x = torch.tensor(1.0, requires_grad=True)
y = torch.tensor(2.0, requires_grad=True)

In [10]:
z = 3*x**2 + 2*x*y + y**2
z.backward()

In [11]:
print(x.grad)  # x에서의 기울기 출력
print(y.grad)  # y에서의 기울기 출력

tensor(10.)
tensor(6.)


4. 연산 그래프 이해
    - 연산 그래프의 생성 및 기울기 계산 과정 이해
    - 각 연산이 그래프의 노드로 표현되고, 역전파를 통해 기울기가 계산

In [12]:
a = torch.tensor([2.0, 3.0], requires_grad=True)
b = torch.tensor([6.0, 4.0], requires_grad=True)

Q = 3*a**3 - b**2
external_grad = torch.tensor([1.0, 1.0])
Q.backward(gradient=external_grad)

print(a.grad)  # a의 기울기 출력
print(b.grad)  # b의 기울기 출력

tensor([36., 81.])
tensor([-12.,  -8.])


5. 실습 및 과제
    - Autograd를 활용한 다양한 함수의 기울기 계산
    - 주어진 함수에 대해 기울기를 계산하고, 기울기를 활용한 간단한 최적화 문제 해결

In [13]:
# 주어진 함수 f(x) = 4x^3 + 2x^2 + x 에 대해 x=1에서의 기울기를 구하세요
x = torch.tensor(1.0, requires_grad=True)
y = 4*x**3 + 2*x**2 + x
y.backward()
print(x.grad)


tensor(17.)


In [14]:
# 다중 변수 함수 f(x, y) = x^2 + y^3 에 대해 x=2, y=3에서의 기울기를 구하세요
x = torch.tensor(2.0, requires_grad=True)
y = torch.tensor(3.0, requires_grad=True)
z = x**2 + y**3
z.backward()
print(x.grad)
print(y.grad)

tensor(4.)
tensor(27.)
