## 신경망

### 내용
1. 신경망 기본 개념
    - 신경망이란 - 인간의 뇌 구조를 모방한 기계학습 모델(Neural Network)
    - 어러개의 레이어로 구성, 각 레이어는 여러 Neuron으로 구성
    - 신경망 구성요소
        - Neuron
        - Layer
        - Weight, Biases
    - Activation Function
        - 뉴런의 출력값을 결정하는 함수
        - 비선형 활성화를 위한 함수

2. PyTorch에서의 신경망 구현
    - torch.nn 모듈 - 신경망 모델을 쉽게 구축할 수 있도록 다양한 레이어와 함수 제공
    - nn.Module 클래스
        - 모든 신경망 모델의 기본 클래스
        - 모델 정의 및 초기화, 순전파(forward) 정의 방법

In [1]:
import torch
import torch.nn as nn
import torch.optim as optim

In [2]:
class SimpleNN(nn.Module):
    def __init__(self):
        super(SimpleNN, self).__init__()
        self.fc1 = nn.Linear(10, 50)
        self.fc2 = nn.Linear(50, 1)

    def forward(self, x):
        x = torch.relu(self.fc1(x))
        x = self.fc2(x)
        return x

3. 기본 신경망 모델 구성
    - nn.Sequential 사용 - 순차적으로 레이어를 쌓아 간단한 신경망 모델을 구축

In [3]:
model = nn.Sequential(
    nn.Linear(10, 50),
    nn.ReLU(),
    nn.Linear(50, 1)
)

- 활성화 함수 사용 예시
    - Sigmoid, Tanh, ReLU

In [4]:
x = torch.randn(10)
relu = nn.ReLU()
sigmoid = nn.Sigmoid()
tanh = nn.Tanh()

print(relu(x))
print(sigmoid(x))
print(tanh(x))

tensor([0.6963, 0.0000, 0.1453, 0.0000, 1.7677, 1.4787, 0.4687, 0.0000, 0.0000,
        0.0000])
tensor([0.6674, 0.2979, 0.5363, 0.2226, 0.8542, 0.8144, 0.6151, 0.4595, 0.4224,
        0.4973])
tensor([ 0.6020, -0.6948,  0.1443, -0.8485,  0.9434,  0.9012,  0.4372, -0.1609,
        -0.3032, -0.0106])


4. 신경망 모델 학습
    - 손실 함수(Loss Function)와 옵티마이저(Optimizer)
        - 손실 함수: 모델의 예측값과 실제값의 차이를 측정
        - nn.MSELoss(), nn.CrossEntropyLoss()
    - 옵티마이저: 손실을 줄이기 위해 가중치를 업데이트
        - optim.SGD, optim.Adam

In [5]:
# 손실 함수와 옵티마이저 설정
criterion = nn.MSELoss()
optimizer = optim.SGD(model.parameters(), lr=0.01)

- 모델 학습 단계
    - 순전파(forward pass): 입력 데이터를 모델에 통과시켜 예측값을 계산
    - 손실 계산: 예측값과 실제값의 차이 계산
    - 역전파(backward pass): 기울기 계산
    - 가중치 업데이트: 옵티마이저를 통해 가중치 조정

In [6]:
# 학습 예시
inputs = torch.randn(10)
targets = torch.randn(1)

for epoch in range(100):  # 100번의 에포크 동안 학습
    optimizer.zero_grad()  # 옵티마이저 초기화
    outputs = model(inputs)  # 순전파
    loss = criterion(outputs, targets)  # 손실 계산
    loss.backward()  # 역전파
    optimizer.step()  # 가중치 업데이트

5. 실습
    - 간단한 신경망 모델을 구축하고, 주어진 데이터를 사용해 학습 및 평가

In [7]:
# 10개의 입력 특징을 가진 데이터셋을 사용하여, 간단한 신경망 모델을 구축하고 학습하세요.
import torch
import torch.nn as nn
import torch.optim as optim

In [8]:
# 데이터 생성
inputs = torch.randn(100, 10)  # 100개의 샘플, 각 샘플은 10개의 특징
targets = torch.randn(100, 1)  # 100개의 샘플에 대한 타겟 값

# 모델 정의
model = nn.Sequential(
    nn.Linear(10, 50),
    nn.ReLU(),
    nn.Linear(50, 1)
)

# 손실 함수와 옵티마이저 설정
criterion = nn.MSELoss()
optimizer = optim.SGD(model.parameters(), lr=0.01)

In [9]:
# 모델 학습
for epoch in range(100):  # 100번의 에포크 동안 학습
    optimizer.zero_grad()  # 옵티마이저 초기화
    outputs = model(inputs)  # 순전파
    loss = criterion(outputs, targets)  # 손실 계산
    loss.backward()  # 역전파
    optimizer.step()  # 가중치 업데이트

In [10]:
# 모델 평가
with torch.no_grad():
    test_inputs = torch.randn(10, 10)  # 10개의 테스트 샘플
    test_outputs = model(test_inputs)
    print(test_outputs)

tensor([[-0.0239],
        [-0.1340],
        [-0.3181],
        [-0.0851],
        [ 0.0280],
        [ 0.3194],
        [-0.1044],
        [ 0.2310],
        [-0.1430],
        [ 0.4344]])
