## PyTorch 시작

### PyTorch 소개

#### PyTorch란?
- PyTorch는 Python 기반의 오픈 소스 머신러닝 라이브러리
- Facebook AI Research (FAIR)에서 개발
- 다른 딥러닝 프레임워크와의 비교
    - PyTorch의 장단점
    - TensorFlow, Keras와 비교
    - 동적 연산 그래프 vs 정적 연산 그래프

#### PyTorch 설치
- PyTorch 공식 웹사이트를 통해 설치
- CUDA (GPU 가속) 설치 여부 선택
- OpenCV나 Tensorflow에 비해 매우 간결, 쉽게 설치 가능 

### PyTorch 기본

#### Tensor 개요, 기본연산
- Tensor
- Numpy와 Tensor의 비교

In [1]:
import torch
import numpy as np

In [2]:
torch.__version__

'2.5.1+cu124'

##### 직접생성

In [3]:
# 직접 생성
t = torch.tensor([1, 2, 3, 4])
t

tensor([1, 2, 3, 4])

##### Numpy 배열에서 생성

In [7]:
np_array = np.array([1, 2, 3, 4])
u = torch.from_numpy(np_array)
u

tensor([1, 2, 3, 4], dtype=torch.int32)

##### 초기화 방법

In [8]:
# 0으로 초기화
x = torch.zeros((2, 3))
x

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [9]:
# 1으로 초기화
y = torch.ones((2, 3))
y

tensor([[1., 1., 1.],
        [1., 1., 1.]])

In [10]:
# random값으로 초기화
z = torch.rand((2, 3))
z

tensor([[0.5663, 0.4153, 0.1678],
        [0.4851, 0.3970, 0.0192]])

##### 기본 연산

In [17]:
a = torch.tensor([1.0, 2.0])
b = torch.tensor([3.0, 4.0])

# 덧셈
c = a + b
c

tensor([4., 6.])

In [16]:
# 곱셈
d = a * b
d

tensor([3., 8.])

In [15]:
# 브로드캐스팅
# 서로 다른 크기를 가진 텐서들 간에 연산을 수행할 수 있도록 자동으로 크기를 맞춰주는 기능
e = torch.tensor([[1.0], [2.0], [3.0]])
f = torch.tensor([1.0, 2.0])
g = e + f
print(g)

tensor([[2., 3.],
        [3., 4.],
        [4., 5.]])


#### 연습

##### [2,4,6,8] 로 주어진 리스트를 텐서로 변환하고, 각 요소에 2를 곱한 결과를 출력하세요 

In [18]:
arr = [2,4,6,8]
tensor = torch.tensor(arr)

In [20]:
tensor * 2

tensor([ 4,  8, 12, 16])

##### 3x4 크기의 랜덤으로 된 텐서를 생성하세요

In [21]:
r_tensor = torch.rand((3, 4))
r_tensor

tensor([[0.4661, 0.2420, 0.4547, 0.1109],
        [0.0934, 0.2895, 0.3584, 0.1540],
        [0.2352, 0.5981, 0.5676, 0.0828]])

In [22]:
torch.max(r_tensor)

tensor(0.5981)

In [23]:
torch.min(r_tensor)

tensor(0.0828)

In [24]:
torch.mean(r_tensor)

tensor(0.3044)