### 파이토치 이전에... 넘파이

In [1]:
import numpy as np
import torch

In [2]:
arr1 = [1,2,3,4,5]
arr2 = np.array([1,2,3,4,5])

#### 둘 사이 비교

In [3]:
arr1

[1, 2, 3, 4, 5]

In [4]:
arr2

array([1, 2, 3, 4, 5])

In [5]:
arr3 = np.array([[1,2],[3,4]])

In [6]:
arr3

array([[1, 2],
       [3, 4]])

In [7]:
arr4 = np.array([[5,6],[7,8]])

In [8]:
arr4

array([[5, 6],
       [7, 8]])

In [9]:
arr3 + arr4

array([[ 6,  8],
       [10, 12]])

In [10]:
arr3 * arr4

array([[ 5, 12],
       [21, 32]])

In [11]:
arr5 = np.arange(10)
arr5

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [12]:
arr5[0]

0

In [13]:
arr5[3:9]

array([3, 4, 5, 6, 7, 8])

In [14]:
arr5[:]

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [15]:
arr6 = np.array([[1,2,3],[4,5,6]])
arr6[0,1]

2

In [16]:
arr6[0,:]

array([1, 2, 3])

In [17]:
arr6[:,0:2]

array([[1, 2],
       [4, 5]])

### 파이토치 텐서

#### Tensor
- 다차원 배열을 처리하기 위한 데이터 구조
    - GPU를 사용하지 못하는 Numpy 문제를 해결하기 위해
    - 1차원 scalar, 2차원 vector(matrix), 3차원부터 tensor로 부름

In [18]:
import torch
import numpy as np

#### 텐서 생성
- torch.tensor() 함수로 생성 가능


In [19]:
data = [[1,2],[3,4]]
t = torch.tensor(data)

In [20]:
print(t, t.dtype, t.shape)

tensor([[1, 2],
        [3, 4]]) torch.int64 torch.Size([2, 2])


##### 2중 리스트로 생성

In [21]:
t2 = torch.tensor([[1,2],[3,4]])
print(t2, t2.dtype, t2.shape)

tensor([[1, 2],
        [3, 4]]) torch.int64 torch.Size([2, 2])


##### device를 지정하여 생성가능
- cpu, cuda:0 (다중 GPU이면 번호사용 가능)

In [22]:
t_cpu = torch.tensor([[1,2],[3,4]], device='cpu')
t_gpu = torch.tensor([[1,2],[3,4]], device='cuda:0')

print(t_cpu)
print(t_gpu)

tensor([[1, 2],
        [3, 4]])
tensor([[1, 2],
        [3, 4]], device='cuda:0')


##### dtype 지정 생성

In [23]:
t_i32 = torch.tensor([[1,2],[3,4]], dtype=torch.int32)
print(t_i32.dtype)

torch.int32


In [24]:
t_f64 = torch.tensor([[1,2],[3,4]], dtype=torch.float64)
print(t_f64.dtype)

torch.float64


In [25]:
## 0부터 9까지 수치로 초기화된 1차원 텐서 생성
t_to10 = torch.arange(0, 10)
print(t_to10)

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])


In [26]:
## 값이 모두 0인 3x2 텐서
t_2d0 = torch.zeros(3, 2)
print(t_2d0, t_2d0.shape, t_2d0.size())

tensor([[0., 0.],
        [0., 0.],
        [0., 0.]]) torch.Size([3, 2]) torch.Size([3, 2])


In [27]:
## 값이 모두 1인 3x2 텐서
t_2d1 = torch.ones(3, 2)
print(t_2d1, t_2d1.shape, t_2d1.size())

tensor([[1., 1.],
        [1., 1.],
        [1., 1.]]) torch.Size([3, 2]) torch.Size([3, 2])


In [28]:
## 표준분포 난수로 3x2 텐서생성 후 GPU로 전송
t_2dr = torch.randn(3, 2).to('cuda:0')
print(t_2dr)

tensor([[ 0.4360, -1.1784],
        [ 0.3976, -0.1088],
        [ 0.0889, -0.8999]], device='cuda:0')


In [29]:
## 텐서를 리스트로 저장
t_data = t_2dr.data.tolist()
print(t_data)
print(type(t_data))

[[0.43597906827926636, -1.1784062385559082], [0.3975588083267212, -0.10883945226669312], [0.08894701302051544, -0.8998609781265259]]
<class 'list'>


##### gpu / cpu 변경

In [30]:
t = torch.rand(10000, 10000)
cpu = torch.device('cpu')
gpu = torch.device('cuda:0')

if torch.cuda.is_available():
    t_gpu = t.to(gpu)
    print(t_gpu)

t_cpu = t_gpu.to(cpu)
print(t_cpu)

tensor([[0.5509, 0.6342, 0.2183,  ..., 0.3780, 0.1344, 0.6092],
        [0.6744, 0.5700, 0.9533,  ..., 0.2797, 0.3379, 0.2457],
        [0.1306, 0.8165, 0.6186,  ..., 0.8640, 0.5534, 0.2418],
        ...,
        [0.6600, 0.1763, 0.9979,  ..., 0.7513, 0.6068, 0.8505],
        [0.0737, 0.6136, 0.8314,  ..., 0.4617, 0.2593, 0.6716],
        [0.1650, 0.7168, 0.3466,  ..., 0.3725, 0.8822, 0.9539]],
       device='cuda:0')
tensor([[0.5509, 0.6342, 0.2183,  ..., 0.3780, 0.1344, 0.6092],
        [0.6744, 0.5700, 0.9533,  ..., 0.2797, 0.3379, 0.2457],
        [0.1306, 0.8165, 0.6186,  ..., 0.8640, 0.5534, 0.2418],
        ...,
        [0.6600, 0.1763, 0.9979,  ..., 0.7513, 0.6068, 0.8505],
        [0.0737, 0.6136, 0.8314,  ..., 0.4617, 0.2593, 0.6716],
        [0.1650, 0.7168, 0.3466,  ..., 0.3725, 0.8822, 0.9539]])


In [31]:
## 다른 텐서로부터 생성
t = torch.rand(3, 2)
t_ones = torch.ones_like(t)
t_zeros = torch.zeros_like(t)

print(t)
print(t_ones)
print(t_zeros)

tensor([[0.2460, 0.5593],
        [0.3464, 0.3721],
        [0.9398, 0.1539]])
tensor([[1., 1.],
        [1., 1.],
        [1., 1.]])
tensor([[0., 0.],
        [0., 0.],
        [0., 0.]])


In [32]:
## Tensor는 FloatTensor의 별칭
t_FT = torch.FloatTensor([[1,2,3],[4,5,6]])
t_T = torch.Tensor([[1,2,3],[4,5,6]])

print(t_FT)
print(t_T)
print(t_FT.type(), t_T.type())

tensor([[1., 2., 3.],
        [4., 5., 6.]])
tensor([[1., 2., 3.],
        [4., 5., 6.]])
torch.FloatTensor torch.FloatTensor


In [33]:
## 텐서 데이터타입 캐스팅
t_T.type(dtype=torch.IntTensor).type()

'torch.IntTensor'

#### Numpy Array <- -> Tensor

In [34]:
# numpy 배열에서 텐서 생성
npArr = np.array([0,1,2,3,4,5,6])
t1 = torch.from_numpy(npArr)
t2 = torch.tensor(npArr)

print(t1, t1.type())
print(t2, t2.type())

tensor([0, 1, 2, 3, 4, 5, 6], dtype=torch.int32) torch.IntTensor
tensor([0, 1, 2, 3, 4, 5, 6], dtype=torch.int32) torch.IntTensor


##### GPU 상 텐서는 변환불가

- CPU로 이동 후 변환

In [35]:
t_cpu = torch.tensor([[1,2],[3,4]])
x = t_cpu.numpy()
print(type(x))

<class 'numpy.ndarray'>


In [36]:
t_gpu = torch.tensor([[1,2],[3,4]], device=gpu)
x = t_gpu.cpu().numpy()
print(type(x))

<class 'numpy.ndarray'>


#### Slicing

In [37]:
t = torch.FloatTensor([[1,2,3],[4,5,6]])

In [38]:
## 스칼라 첨자 지정
print(t[0, 2])

tensor(3.)


In [39]:
## 슬라이스로 지정
print(t[:, :2])

tensor([[1., 2.],
        [4., 5.]])


In [40]:
## 리스트로 지정
print(t[:, [1,2]])

tensor([[2., 3.],
        [5., 6.]])


In [41]:
## 마스크 배열이용 
print(t[t > 4]) ## 요소값이 4보다 큰 값

tensor([5., 6.])


In [42]:
## 마스크 배열이용 
print(t[t % 2 == 0]) ## 요소값이 짝수인 값

tensor([2., 4., 6.])


In [43]:
## [0,1]의 요소를 100으로 설정
t[0,1] = 100
print(t)

tensor([[  1., 100.,   3.],
        [  4.,   5.,   6.]])


In [44]:
## 슬라이스를 사용한 일괄 대입
t[:, :-1] = 200
print(t)

tensor([[200., 200.,   3.],
        [200., 200.,   6.]])


In [45]:
## 마스크 배열을 이용한 특정 조건 요소 치환
t[t > 10] = 20
print(t)

tensor([[20., 20.,  3.],
        [20., 20.,  6.]])


### 텐서 연산

- 사칙연산이나 수학 함수, 선형 대수 계산 등이 가능

- 행렬곱 / 특이값 분해 등의 선형대수 계산은 GPU 계산 가능, 대규모 처리 시 Numpy/Scipy 보다 처리속도 빠름

- 동일한 형의 텐서 간의 연산만 가능
    - FloatTensor 와 DoubleTensor 연산 신에는 오류

#### Broadcasting

In [46]:
m1 = torch.FloatTensor([[3,3]])
m2 = torch.FloatTensor([[2,2]])
print(m1 + m2)

tensor([[5., 5.]])


In [47]:
m3 = torch.FloatTensor([[1,2]])
m4 = torch.FloatTensor([3])
print(m3 + m4)

tensor([[4., 5.]])


In [48]:
m5 = torch.FloatTensor([[1,2]])
m6 = torch.FloatTensor([[3],[4]])
print(m5 + m6)

tensor([[4., 5.],
        [5., 6.]])


#### Multiplication

In [49]:
m1 = torch.FloatTensor([[1,2],[3,4]])
m2 = torch.FloatTensor([[1],[2]])
print(f'Shape of Matrix 1: {m1.shape}')
print(f'Shape of Matrix 2: {m2.shape}')

Shape of Matrix 1: torch.Size([2, 2])
Shape of Matrix 2: torch.Size([2, 1])


In [50]:
m1

tensor([[1., 2.],
        [3., 4.]])

In [51]:
m2

tensor([[1.],
        [2.]])

##### 행렬곱 연산

In [52]:
print(torch.mm(m1, m2))

tensor([[ 5.],
        [11.]])


In [53]:
print(m1.matmul(m2))

tensor([[ 5.],
        [11.]])


In [54]:
print(torch.matmul(m1, m2))

tensor([[ 5.],
        [11.]])


##### 곱 연산

In [55]:
m1.mul(m2)

tensor([[1., 2.],
        [6., 8.]])

In [56]:
torch.mul(m1, m2)

tensor([[1., 2.],
        [6., 8.]])

In [57]:
m1 * m2

tensor([[1., 2.],
        [6., 8.]])

#### 요소별 연산 (Element-wise Operation)

- sin, cos, tan, abs, exp, log, sqrt 등 텐서 각 요소에 사용할 수 있는 연사

In [58]:
m1 = torch.FloatTensor([[1,2,3],[4,5,6]])
m2 = torch.FloatTensor([[1,2,3],[4,5,6]])

In [59]:
## 텐서 요소간 나누기
torch.div(m1, m2)

tensor([[1., 1., 1.],
        [1., 1., 1.]])

In [60]:
## 텐서 요소 제곱
torch.pow(m1, 2)

tensor([[ 1.,  4.,  9.],
        [16., 25., 36.]])

In [61]:
m1**2

tensor([[ 1.,  4.,  9.],
        [16., 25., 36.]])

In [62]:
## 텐서 요소 지수 연산
torch.exp(m1)

tensor([[  2.7183,   7.3891,  20.0855],
        [ 54.5981, 148.4132, 403.4288]])

In [63]:
## 텐소 요소 로그 연산
torch.log(m1)

tensor([[0.0000, 0.6931, 1.0986],
        [1.3863, 1.6094, 1.7918]])

In [64]:
torch.sin(m1)

tensor([[ 0.8415,  0.9093,  0.1411],
        [-0.7568, -0.9589, -0.2794]])

#### 통계함수
- sum, max, min, mean, std 등 

In [65]:
t = torch.FloatTensor([1,2])
t.mean()

tensor(1.5000)

In [66]:
t = torch.FloatTensor([[1,2],[3,4]])
t.mean()

tensor(2.5000)

In [67]:
t

tensor([[1., 2.],
        [3., 4.]])

In [68]:
# 아래방향(행방향)
t.mean(dim=0)

tensor([2., 3.])

In [69]:
# 가로방향(열방향)
t.mean(dim=1)

tensor([1.5000, 3.5000])

In [70]:
t.sum()

tensor(10.)

In [71]:
t.sum(dim=0)

tensor([4., 6.])

In [72]:
t.sum(dim=1)

tensor([3., 7.])

In [73]:
t = torch.FloatTensor([[1,2],[3,4]])

In [74]:
## 최대값
m = t.max()

In [75]:
m

tensor(4.)

In [76]:
m.item()

4.0

In [77]:
t.max(dim=0)

torch.return_types.max(
values=tensor([3., 4.]),
indices=tensor([1, 1]))

In [78]:
t.max(dim=1)

torch.return_types.max(
values=tensor([2., 4.]),
indices=tensor([1, 1]))

### 텐서 조작 (Tensor Manipulation)

- 원소의 수를 유지하면서 텐서의 Shape를 변경 - view(), reshape()
- 텐서의 차원을 교환 - transpose()
- 복수의 텐서를 하나로 연결 - cat(), stack()

#### View
- 원하는 형태로 reshape

In [79]:
t = torch.FloatTensor([[[0,1,2],
                        [3,4,5]],
                        [[6,7,8],
                         [9,10,11]]])

In [80]:
t

tensor([[[ 0.,  1.,  2.],
         [ 3.,  4.,  5.]],

        [[ 6.,  7.,  8.],
         [ 9., 10., 11.]]])

In [81]:
## 3차원
t.shape

torch.Size([2, 2, 3])

In [82]:
## 4x3으로 변경
t.view([4,3])

tensor([[ 0.,  1.,  2.],
        [ 3.,  4.,  5.],
        [ 6.,  7.,  8.],
        [ 9., 10., 11.]])

In [84]:
t.view([4,3]).shape

torch.Size([4, 3])

In [85]:
t.view([-1,3])  # -1은 다른 차원에서 유추

tensor([[ 0.,  1.,  2.],
        [ 3.,  4.,  5.],
        [ 6.,  7.,  8.],
        [ 9., 10., 11.]])

In [86]:
t.view([2,-1]) # 2x6 로 변경

tensor([[ 0.,  1.,  2.,  3.,  4.,  5.],
        [ 6.,  7.,  8.,  9., 10., 11.]])

In [88]:
t.view([4,-1]) # 컬럼을 유추

tensor([[ 0.,  1.,  2.],
        [ 3.,  4.,  5.],
        [ 6.,  7.,  8.],
        [ 9., 10., 11.]])

In [89]:
t.view([-1,1,3]) # 텐서를 (?, 1, 3)으로 변경

tensor([[[ 0.,  1.,  2.]],

        [[ 3.,  4.,  5.]],

        [[ 6.,  7.,  8.]],

        [[ 9., 10., 11.]]])

In [90]:
t.view([-1,1,3]).shape

torch.Size([4, 1, 3])

##### view()를 reshape() 로 바꾸어도 결과는 동일

#### 차원 재구성
- transpose(): 2개 차원을 변경

In [91]:
t = torch.rand(16, 32, 3)

In [92]:
t

tensor([[[0.8058, 0.7940, 0.4314],
         [0.2764, 0.7868, 0.8834],
         [0.0773, 0.9429, 0.5034],
         ...,
         [0.6602, 0.8295, 0.1347],
         [0.4602, 0.5594, 0.5101],
         [0.7429, 0.6732, 0.8693]],

        [[0.6128, 0.7138, 0.7771],
         [0.0166, 0.9125, 0.8562],
         [0.4751, 0.2014, 0.7067],
         ...,
         [0.7714, 0.9087, 0.3285],
         [0.8146, 0.3066, 0.5896],
         [0.3962, 0.2339, 0.7013]],

        [[0.6434, 0.1588, 0.7310],
         [0.1294, 0.4524, 0.3277],
         [0.0999, 0.2462, 0.6981],
         ...,
         [0.2971, 0.9224, 0.7955],
         [0.8421, 0.9354, 0.8447],
         [0.6431, 0.9703, 0.6795]],

        ...,

        [[0.2319, 0.5992, 0.3082],
         [0.2196, 0.4495, 0.1158],
         [0.9896, 0.7727, 0.1438],
         ...,
         [0.1606, 0.5078, 0.0245],
         [0.0478, 0.6057, 0.1784],
         [0.2816, 0.2954, 0.6690]],

        [[0.3153, 0.5288, 0.3038],
         [0.8022, 0.2005, 0.6444],
         [0.

In [93]:
t.shape

torch.Size([16, 32, 3])

In [96]:
t_t = t.transpose(0, 2) # 요소 0과 2를 바꿈

In [95]:
print(f't.shape = {t.shape} / t_t.shape = {t_t.shape}')

t.shape = torch.Size([16, 32, 3]) / t_t.shape = torch.Size([3, 32, 16])


In [97]:
t_t_t = t.transpose(0, 1)

In [98]:
t_t_t.shape

torch.Size([32, 16, 3])

In [99]:
## CHW를 HWC로 변환 - Channels, Height, Width
hwc = torch.rand(100, 3, 32, 64)

In [100]:
chw = hwc.transpose(1,2).transpose(2,3)

In [101]:
print(hwc.shape, chw.shape)

torch.Size([100, 3, 32, 64]) torch.Size([100, 32, 64, 3])


#### 차원 재구성
- permute(): 모든 차원의 순서 재배치

In [102]:
hwc = torch.rand(100, 3, 32, 64)

In [103]:
chw = hwc.permute(0, 2, 3, 1)

In [104]:
print(hwc.shape, chw.shape)

torch.Size([100, 3, 32, 64]) torch.Size([100, 32, 64, 3])


#### Squeeze
- squeeze() : 차원의 원소가 1인 차원을 축소(축 제거)

In [105]:
ft = torch.FloatTensor([[0],[1],[2]])
ft

tensor([[0.],
        [1.],
        [2.]])

In [107]:
ft.shape

torch.Size([3, 1])

In [106]:
ft.squeeze()

tensor([0., 1., 2.])

In [108]:
ft.squeeze().shape

torch.Size([3])

#### Unsqueez
- unsqueeze() : 해당 위치의 자원을 증가

In [109]:
t1 = torch.Tensor(10, 3, 4)
t2 = torch.unsqueeze(t1, dim=0)

In [110]:
t1.size()

torch.Size([10, 3, 4])

In [111]:
t2.size()

torch.Size([1, 10, 3, 4])

In [112]:
t3 = torch.unsqueeze(t1, dim=1)
t3.size()

torch.Size([10, 1, 3, 4])

#### 텐서 결합
- cat() : concatenate

In [113]:
t1 = torch.FloatTensor([[1,2,3],[4,5,6]])
t2 = torch.FloatTensor([[-1,-2,-3],[-4,-5,-6]])

In [114]:
torch.cat([t1, t2], dim=0)

tensor([[ 1.,  2.,  3.],
        [ 4.,  5.,  6.],
        [-1., -2., -3.],
        [-4., -5., -6.]])

In [115]:
torch.cat([t1, t2], dim=1)

tensor([[ 1.,  2.,  3., -1., -2., -3.],
        [ 4.,  5.,  6., -4., -5., -6.]])

- stack()

In [116]:
torch.stack([t1, t2, t1, t2], dim=0)

tensor([[[ 1.,  2.,  3.],
         [ 4.,  5.,  6.]],

        [[-1., -2., -3.],
         [-4., -5., -6.]],

        [[ 1.,  2.,  3.],
         [ 4.,  5.,  6.]],

        [[-1., -2., -3.],
         [-4., -5., -6.]]])

#### 텐서 분리
- split()

In [117]:
t = torch.FloatTensor([
    [1,2,3],
    [4,5,6],
    [-1,-2,-3],
    [-4,-5,-6]
])

In [118]:
t

tensor([[ 1.,  2.,  3.],
        [ 4.,  5.,  6.],
        [-1., -2., -3.],
        [-4., -5., -6.]])

In [119]:
torch.split(t, 2, dim=0)

(tensor([[1., 2., 3.],
         [4., 5., 6.]]),
 tensor([[-1., -2., -3.],
         [-4., -5., -6.]]))

In [120]:
t1, t2 = torch.split(t, 2, dim=0)

In [121]:
t1

tensor([[1., 2., 3.],
        [4., 5., 6.]])

In [122]:
torch.split(t, 2, dim=1)

(tensor([[ 1.,  2.],
         [ 4.,  5.],
         [-1., -2.],
         [-4., -5.]]),
 tensor([[ 3.],
         [ 6.],
         [-3.],
         [-6.]]))

In [123]:
t3, t4 = torch.split(t, 2, dim=1)

In [124]:
t4

tensor([[ 3.],
        [ 6.],
        [-3.],
        [-6.]])

In [125]:
ts = torch.split(t, 2, dim=1)

In [126]:
ts

(tensor([[ 1.,  2.],
         [ 4.,  5.],
         [-1., -2.],
         [-4., -5.]]),
 tensor([[ 3.],
         [ 6.],
         [-3.],
         [-6.]]))