### Pytorch 텐서 테스트

In [1]:
import torch
import numpy as np

#### Vector, Matrix, Tensor
- 벡터
	- 1차원 - 벡터
	- 2차원 - 매트릭트
	- 3차원이상 - 텐서

	<img src="https://raw.githubusercontent.com/hugoMGSung/study-pytorch/main/images/torch0003.png" width="730">

In [17]:
basic_data = [1,3,5]
tensor_data1 = torch.Tensor(basic_data) # vector

print(tensor_data1)

tensor([1., 3., 5.])


In [18]:
print(f'tensor type : {type(tensor_data1)}, tensor shape : {tensor_data1.shape}')
print(f'tensor dtype : {tensor_data1.dtype}, tensor device : {tensor_data1.device}')

tensor type : <class 'torch.Tensor'>, tensor shape : torch.Size([3])
tensor dtype : torch.float32, tensor device : cpu


#### GPU 사용하기

In [14]:
if torch.cuda.is_available():
	tensor_data = tensor_data1.to('cuda')

print(f'tensor type : {type(tensor_data)}, tensor shape : {tensor_data.shape}')
print(f'tensor dtype : {tensor_data.dtype}, tensor device : {tensor_data.device}')

tensor type : <class 'torch.Tensor'>, tensor shape : torch.Size([3])
tensor dtype : torch.float32, tensor device : cuda:0


In [15]:
basic_data = [ [0, 2, 4], [6, 8, 10] ]
tensor_data1 = torch.Tensor(basic_data)

if torch.cuda.is_available():
	tensor_data = tensor_data1.to('cuda')
	
print(tensor_data)

print(f'tensor type : {type(tensor_data)}, tensor shape : {tensor_data.shape}')
print(f'tensor dtype : {tensor_data.dtype}, tensor device : {tensor_data.device}')

tensor([[ 0.,  2.,  4.],
        [ 6.,  8., 10.]], device='cuda:0')
tensor type : <class 'torch.Tensor'>, tensor shape : torch.Size([2, 3])
tensor dtype : torch.float32, tensor device : cuda:0


In [20]:
np_data = np.array(basic_data)

print(np_data)

tensor_data2 = torch.from_numpy(np_data) # 기본은 float()

print(tensor_data2)
print(f'tensor dtype : {tensor_data2.dtype}, tensor device : {tensor_data2.device}')

[1 3 5]
tensor([1, 3, 5], dtype=torch.int32)
tensor dtype : torch.int32, tensor device : cpu


In [22]:
tensor_data3 = torch.from_numpy(np_data).double() ## double은 float64 

print(tensor_data3)
print(f'tensor dtype : {tensor_data3.dtype}, tensor device : {tensor_data3.device}')

tensor([1., 3., 5.], dtype=torch.float64)
tensor dtype : torch.float64, tensor device : cpu
