### Pytorch 텐서 테스트

In [2]:
import torch
import numpy as np

#### Vector, Matrix, Tensor
- 텐서
	- 1차원 - 벡터
	- 2차원 - 매트릭트
	- 3차원이상 - 텐서

	<img src="https://raw.githubusercontent.com/hugoMGSung/study-pytorch/main/images/torch0003.png" width="730">


- Numpy는 n차원 배열 객체생성과 조작을 위한 다양한 함수를 제공. 연산 그래프나 딥러닝, 변화도 등은 알지 못함.
- GPU를 사용한 수치 연산 가속화 불가능
- PyTorch 모델의 입력, 출력, 모델 매개변수의 인코드 처리

In [3]:
basic_data = [1,3,5]
tensor_data1 = torch.Tensor(basic_data) # vector

print(tensor_data1)

tensor([1., 3., 5.])


In [4]:
print(f'tensor type : {type(tensor_data1)}, tensor shape : {tensor_data1.shape}')
print(f'tensor dtype : {tensor_data1.dtype}, tensor device : {tensor_data1.device}')

tensor type : <class 'torch.Tensor'>, tensor shape : torch.Size([3])
tensor dtype : torch.float32, tensor device : cpu


#### GPU 사용하기

In [5]:
if torch.cuda.is_available():
	tensor_data = tensor_data1.to('cuda')

print(f'tensor type : {type(tensor_data)}, tensor shape : {tensor_data.shape}')
print(f'tensor dtype : {tensor_data.dtype}, tensor device : {tensor_data.device}')

tensor type : <class 'torch.Tensor'>, tensor shape : torch.Size([3])
tensor dtype : torch.float32, tensor device : cuda:0


In [6]:
basic_data = [ [0, 2, 4], [6, 8, 10] ]
tensor_data1 = torch.Tensor(basic_data)

if torch.cuda.is_available():
	tensor_data = tensor_data1.to('cuda')
	
print(tensor_data)

print(f'tensor type : {type(tensor_data)}, tensor shape : {tensor_data.shape}')
print(f'tensor dtype : {tensor_data.dtype}, tensor device : {tensor_data.device}')

tensor([[ 0.,  2.,  4.],
        [ 6.,  8., 10.]], device='cuda:0')
tensor type : <class 'torch.Tensor'>, tensor shape : torch.Size([2, 3])
tensor dtype : torch.float32, tensor device : cuda:0


In [7]:
np_data = np.array(basic_data)

print(np_data)

tensor_data2 = torch.from_numpy(np_data) # 기본은 float()

print(tensor_data2)
print(f'tensor dtype : {tensor_data2.dtype}, tensor device : {tensor_data2.device}')

[[ 0  2  4]
 [ 6  8 10]]
tensor([[ 0,  2,  4],
        [ 6,  8, 10]], dtype=torch.int32)
tensor dtype : torch.int32, tensor device : cpu


#### 텐서 연습

In [8]:
mat1 = torch.FloatTensor([[1,2], [3,4]])
mat2 = torch.IntTensor([[1,2], [3,4]])

In [9]:
print(mat1.shape)
print(mat2.shape)

torch.Size([2, 2])
torch.Size([2, 2])


In [10]:
print(mat1.type())
print(mat2.type())

torch.FloatTensor
torch.IntTensor


In [11]:
mat1 = torch.FloatTensor([[1,2], [3,4]])
mat2 = torch.FloatTensor([[1], [2]])

mat1 = mat1.to('cuda')
mat2 = mat2.to('cuda')

In [12]:
mat1.matmul(mat2)

tensor([[ 5.],
        [11.]], device='cuda:0')

In [13]:
mat1 * mat2

tensor([[1., 2.],
        [6., 8.]], device='cuda:0')

In [14]:
mat1.mul(mat2)

tensor([[1., 2.],
        [6., 8.]], device='cuda:0')

<img src="https://camo.githubusercontent.com/e76d463dd069d496943ecd10a3d8970237f7cf8b431fb5fd797f50b66bb01a8f/68747470733a2f2f77696b69646f63732e6e65742f696d616765732f706167652f35323834362f6e6577696d6167652e706e67" Width="700">

#### 기본 사용법 다시

##### 텐서 생성

In [15]:
## 0에서 1사이의 랜덤숫자 생성
torch.rand(2, 3)

tensor([[0.2051, 0.5971, 0.1002],
        [0.9509, 0.3269, 0.7630]])

In [16]:
## 0에서 1사이의 정규분포로 샘플링한 랜덤숫자 생성
torch.randn(2, 3)

tensor([[-1.1616,  0.2232, -0.6556],
        [ 0.1820,  0.3430, -0.5206]])

In [17]:
## 시작수와 종료수 사이의 랜덤숫자 생성
torch.randint(0, 9, size=(2, 3))

tensor([[3, 4, 0],
        [6, 6, 6]])

##### 초기화

In [18]:
## 0 초기화 텐서
torch.zeros(2,3)

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [19]:
## 1초기화 텐서
torch.ones(2, 3)

tensor([[1., 1., 1.],
        [1., 1., 1.]])

In [20]:
## 0 초기화 방법2
ref = torch.rand(4, 5)
torch.zeros_like(ref)

tensor([[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]])

In [21]:
## 1 초기화 방법2
torch.ones_like(ref)

tensor([[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]])

##### 텐서 데이터타입

In [22]:
## 데이터타입 확인법 / FloatTensor(기본)
ref.type()

'torch.FloatTensor'

In [23]:
## DoubleTensor
x = torch.rand(2, 3)
x_d = x.type(dtype = torch.DoubleTensor)
x_d.type()

'torch.DoubleTensor'

In [24]:
## IntTensor
x.type_as(torch.IntTensor()).type()

'torch.IntTensor'

##### Numpy를 Tensor로

In [32]:
## 넘파이로 배열 생성
x1 = np.ndarray(shape=(2,3), dtype=int, buffer=np.array([1,2,3,4,5,6]))
x1, type(x1)

(array([[1, 2, 3],
        [4, 5, 6]]),
 numpy.ndarray)

In [33]:
## 텐서로 이동
x2 = torch.from_numpy(x1)
x2, x2.type()

(tensor([[1, 2, 3],
         [4, 5, 6]], dtype=torch.int32),
 'torch.IntTensor')

In [34]:
## 다시 넘파이로
x3 = x2.numpy()
x3, type(x3)

(array([[1, 2, 3],
        [4, 5, 6]]),
 numpy.ndarray)

##### CPU사용 GPU사용

In [35]:
## 배열로 텐서 생성
x4 = torch.FloatTensor([[1,2,3],[4,5,6]])
x4, x4.type()

(tensor([[1., 2., 3.],
         [4., 5., 6.]]),
 'torch.FloatTensor')

In [36]:
## 디바이스 만들어놓기
cpu = torch.device('cpu')
gpu = torch.device('cuda')

x5_normal = x4.to(cpu)
print(x5_normal)

if torch.cuda.is_available():
	x6_gpu = x5_normal.to(gpu)
	print(x6_gpu)

tensor([[1., 2., 3.],
        [4., 5., 6.]])
tensor([[1., 2., 3.],
        [4., 5., 6.]], device='cuda:0')


In [38]:
## 텐서 크기
x7 = torch.FloatTensor(5, 10, 20, 40)
x7.size(), x7.size()[2:3]

(torch.Size([5, 10, 20, 40]), torch.Size([20]))

##### 인덱스, 조인, 자르기

In [39]:
x8 = torch.randn(4, 3)
x8

tensor([[ 1.1806,  0.8735,  2.2158],
        [-2.4749, -1.4526, -0.3232],
        [-0.0673,  3.3029,  2.0970],
        [-0.0226, -1.2023, -0.7906]])

In [42]:
## 앞엔 행 인덱스, 뒤는 열 인덱스
x8[1:3, 1:2]

tensor([[-1.4526],
        [ 3.3029]])

In [50]:
## 아래와 동일한 기능
x8[1:3, :]

tensor([[-2.4749, -1.4526, -0.3232],
        [-0.0673,  3.3029,  2.0970]])

In [48]:
## index_select 함수로도 가능
## dim : 0(행별), 1(열별), -1(마지막 차원끼리) 계산
torch.index_select(x8, dim=0, index=torch.LongTensor([1, 2]))

tensor([[-2.4749, -1.4526, -0.3232],
        [-0.0673,  3.3029,  2.0970]])

In [62]:
## Join
x = torch.FloatTensor([[1,2,3],[4,5,6]])
y = torch.FloatTensor([[-1,-2,-3],[-4,-5,-6]])
z1 = torch.cat([x,y], dim=0)
z2 = torch.cat([x,y], dim=1)

x, y, z1, z2

(tensor([[1., 2., 3.],
         [4., 5., 6.]]),
 tensor([[-1., -2., -3.],
         [-4., -5., -6.]]),
 tensor([[ 1.,  2.,  3.],
         [ 4.,  5.,  6.],
         [-1., -2., -3.],
         [-4., -5., -6.]]),
 tensor([[ 1.,  2.,  3., -1., -2., -3.],
         [ 4.,  5.,  6., -4., -5., -6.]]))

In [63]:
x = torch.FloatTensor([[1,2,3],[4,5,6]])
x_stack = torch.stack([x, x, x, x], dim=0)

x_stack, x_stack.size()

(tensor([[[1., 2., 3.],
          [4., 5., 6.]],
 
         [[1., 2., 3.],
          [4., 5., 6.]],
 
         [[1., 2., 3.],
          [4., 5., 6.]],
 
         [[1., 2., 3.],
          [4., 5., 6.]]]),
 torch.Size([4, 2, 3]))

In [64]:
## Slicing
x_1, x_2 = torch.chunk(z1, 2, dim=0)
y_1, y_2, y_3 = torch.chunk(z1, 3, dim=1)

z1, x_1, x_2, z1, y_1, y_2, y_3

(tensor([[ 1.,  2.,  3.],
         [ 4.,  5.,  6.],
         [-1., -2., -3.],
         [-4., -5., -6.]]),
 tensor([[1., 2., 3.],
         [4., 5., 6.]]),
 tensor([[-1., -2., -3.],
         [-4., -5., -6.]]),
 tensor([[ 1.,  2.,  3.],
         [ 4.,  5.,  6.],
         [-1., -2., -3.],
         [-4., -5., -6.]]),
 tensor([[ 1.],
         [ 4.],
         [-1.],
         [-4.]]),
 tensor([[ 2.],
         [ 5.],
         [-2.],
         [-5.]]),
 tensor([[ 3.],
         [ 6.],
         [-3.],
         [-6.]]))

In [65]:
x1, x2 = torch.split(z1, 2, dim=0)
y1 = torch.split(z1, 2, dim=1) 

print(z1, x1, x2, sep="\n")

print("\nThis is y1:")
for i in y1:
  print(i)

tensor([[ 1.,  2.,  3.],
        [ 4.,  5.,  6.],
        [-1., -2., -3.],
        [-4., -5., -6.]])
tensor([[1., 2., 3.],
        [4., 5., 6.]])
tensor([[-1., -2., -3.],
        [-4., -5., -6.]])

This is y1:
tensor([[ 1.,  2.],
        [ 4.,  5.],
        [-1., -2.],
        [-4., -5.]])
tensor([[ 3.],
        [ 6.],
        [-3.],
        [-6.]])


In [67]:
## Squeezing
## 길이가 1인 차원들은 압축하기
x1 = torch.FloatTensor(10, 1, 3, 1, 4, 5)
x2 = torch.squeeze(x1)

x1.size(), x2.size()

(torch.Size([10, 1, 3, 1, 4, 5]), torch.Size([10, 3, 4, 5]))

In [68]:
## 차원을 늘림
x3 = torch.unsqueeze(x2, dim=0)

x2.size(), x3.size()

(torch.Size([10, 3, 4, 5]), torch.Size([1, 10, 3, 4, 5]))

##### 텐서값 초기화

In [60]:
import torch.nn.init as init

init1 = init.uniform_(torch.FloatTensor(2, 3), a= 0, b=9)

init2 = init.normal_(torch.FloatTensor(2, 3), std=0.2)

init3 = init.constant_(torch.FloatTensor(2, 3), 3.141592)

init1, init2, init3

(tensor([[7.2287, 8.2722, 1.2661],
         [7.9687, 3.8892, 4.4951]]),
 tensor([[ 0.0611,  0.1081, -0.1068],
         [ 0.0126,  0.0316,  0.1204]]),
 tensor([[3.1416, 3.1416, 3.1416],
         [3.1416, 3.1416, 3.1416]]))

##### 수학연산

In [61]:
x1 = torch.FloatTensor([[1,2,3],[4,5,6]])
x2 = torch.FloatTensor([[1,2,3],[4,5,6]])
add = torch.add(x1, x2)

x1, x2, add, x1+x2, x1-x2

(tensor([[1., 2., 3.],
         [4., 5., 6.]]),
 tensor([[1., 2., 3.],
         [4., 5., 6.]]),
 tensor([[ 2.,  4.,  6.],
         [ 8., 10., 12.]]),
 tensor([[ 2.,  4.,  6.],
         [ 8., 10., 12.]]),
 tensor([[0., 0., 0.],
         [0., 0., 0.]]))

In [70]:
x1 = torch.FloatTensor([[1,2,3],[4,5,6]])
x2 = torch.FloatTensor([[1,2,3],[4,5,6]])
x3 = torch.mul(x1, x2)

x3

tensor([[ 1.,  4.,  9.],
        [16., 25., 36.]])

In [71]:
x1 = torch.FloatTensor([[1,2,3],[4,5,6]])
x2 = torch.FloatTensor([[1,2,3],[4,5,6]])
x3 = torch.div(x1, x2)

x3

tensor([[1., 1., 1.],
        [1., 1., 1.]])

In [83]:
x1 = torch.FloatTensor(3, 4)
x1

tensor([[0.0000, 3.5156, 0.0000, 4.0000],
        [0.0000, 4.5156, 0.0000, 5.0625],
        [0.0000, 5.3477, 0.0000, 5.6406]])

In [84]:
torch.pow(x1, 2), x1**2

(tensor([[ 0.0000, 12.3596,  0.0000, 16.0000],
         [ 0.0000, 20.3909,  0.0000, 25.6289],
         [ 0.0000, 28.5974,  0.0000, 31.8167]]),
 tensor([[ 0.0000, 12.3596,  0.0000, 16.0000],
         [ 0.0000, 20.3909,  0.0000, 25.6289],
         [ 0.0000, 28.5974,  0.0000, 31.8167]]))

In [ ]:
## 기타 수식연산
## torch.pow, torch.exp, torch.log, ...

In [91]:
## Matrix 연산
x1 = torch.FloatTensor(3,4)
x2 = torch.FloatTensor(4,5)

torch.mm(x1,x2)

tensor([[ 58.2642,   0.0000,  61.8091,   0.0000,  64.5816],
        [ 94.5884,   0.0000, 100.3409,   0.0000, 104.8189],
        [124.4028,   0.0000, 131.9546,   0.0000, 137.7190]])

In [ ]:
## 기타 매트릭스
# torch.mm, torch.bmm, torch.dot, torch.transpose