### Pytorch 텐서 테스트

In [1]:
import torch
import numpy as np

#### Vector, Matrix, Tensor
- 텐서
	- 1차원 - 벡터
	- 2차원 - 매트릭트
	- 3차원이상 - 텐서

	<img src="https://raw.githubusercontent.com/hugoMGSung/study-pytorch/main/images/torch0003.png" width="730">


- Numpy는 n차원 배열 객체생성과 조작을 위한 다양한 함수를 제공. 연산 그래프나 딥러닝, 변화도 등은 알지 못함.
- GPU를 사용한 수치 연산 가속화 불가능
- PyTorch 모델의 입력, 출력, 모델 매개변수의 인코드 처리

In [2]:
basic_data = [1,3,5]
tensor_data1 = torch.Tensor(basic_data) # vector

print(tensor_data1)

tensor([1., 3., 5.])


In [3]:
print(f'tensor type : {type(tensor_data1)}, tensor shape : {tensor_data1.shape}')
print(f'tensor dtype : {tensor_data1.dtype}, tensor device : {tensor_data1.device}')

tensor type : <class 'torch.Tensor'>, tensor shape : torch.Size([3])
tensor dtype : torch.float32, tensor device : cpu


#### GPU 사용하기

In [4]:
if torch.cuda.is_available():
	tensor_data = tensor_data1.to('cuda')

print(f'tensor type : {type(tensor_data)}, tensor shape : {tensor_data.shape}')
print(f'tensor dtype : {tensor_data.dtype}, tensor device : {tensor_data.device}')

tensor type : <class 'torch.Tensor'>, tensor shape : torch.Size([3])
tensor dtype : torch.float32, tensor device : cuda:0


In [5]:
basic_data = [ [0, 2, 4], [6, 8, 10] ]
tensor_data1 = torch.Tensor(basic_data)

if torch.cuda.is_available():
	tensor_data = tensor_data1.to('cuda')
	
print(tensor_data)

print(f'tensor type : {type(tensor_data)}, tensor shape : {tensor_data.shape}')
print(f'tensor dtype : {tensor_data.dtype}, tensor device : {tensor_data.device}')

tensor([[ 0.,  2.,  4.],
        [ 6.,  8., 10.]], device='cuda:0')
tensor type : <class 'torch.Tensor'>, tensor shape : torch.Size([2, 3])
tensor dtype : torch.float32, tensor device : cuda:0


In [6]:
np_data = np.array(basic_data)

print(np_data)

tensor_data2 = torch.from_numpy(np_data) # 기본은 float()

print(tensor_data2)
print(f'tensor dtype : {tensor_data2.dtype}, tensor device : {tensor_data2.device}')

[[ 0  2  4]
 [ 6  8 10]]
tensor([[ 0,  2,  4],
        [ 6,  8, 10]], dtype=torch.int32)
tensor dtype : torch.int32, tensor device : cpu


#### 텐서 연습

In [7]:
mat1 = torch.FloatTensor([[1,2], [3,4]])
mat2 = torch.IntTensor([[1,2], [3,4]])

In [12]:
print(mat1.shape)
print(mat2.shape)

torch.Size([2, 2])
torch.Size([2, 2])


In [13]:
print(mat1.type())
print(mat2.type())

torch.FloatTensor
torch.IntTensor


In [15]:
mat1 = torch.FloatTensor([[1,2], [3,4]])
mat2 = torch.FloatTensor([[1], [2]])

mat1 = mat1.to('cuda')
mat2 = mat2.to('cuda')

In [16]:
mat1.matmul(mat2)

tensor([[ 5.],
        [11.]], device='cuda:0')

In [17]:
mat1 * mat2

tensor([[1., 2.],
        [6., 8.]], device='cuda:0')

In [18]:
mat1.mul(mat2)

tensor([[1., 2.],
        [6., 8.]], device='cuda:0')

<img src="https://camo.githubusercontent.com/e76d463dd069d496943ecd10a3d8970237f7cf8b431fb5fd797f50b66bb01a8f/68747470733a2f2f77696b69646f63732e6e65742f696d616765732f706167652f35323834362f6e6577696d6167652e706e67" Width="700">