### Pytorch 텐서 테스트

In [28]:
import torch
import numpy as np

#### Vector, Matrix, Tensor
- 텐서
	- 1차원 - 벡터
	- 2차원 - 매트릭트
	- 3차원이상 - 텐서

	<img src="https://raw.githubusercontent.com/hugoMGSung/study-pytorch/main/images/torch0003.png" width="730">


- Numpy는 n차원 배열 객체생성과 조작을 위한 다양한 함수를 제공. 연산 그래프나 딥러닝, 변화도 등은 알지 못함.
- GPU를 사용한 수치 연산 가속화 불가능
- PyTorch 모델의 입력, 출력, 모델 매개변수의 인코드 처리

In [2]:
basic_data = [1,3,5]
tensor_data1 = torch.Tensor(basic_data) # vector

print(tensor_data1)

tensor([1., 3., 5.])


In [3]:
print(f'tensor type : {type(tensor_data1)}, tensor shape : {tensor_data1.shape}')
print(f'tensor dtype : {tensor_data1.dtype}, tensor device : {tensor_data1.device}')

tensor type : <class 'torch.Tensor'>, tensor shape : torch.Size([3])
tensor dtype : torch.float32, tensor device : cpu


#### GPU 사용하기

In [4]:
if torch.cuda.is_available():
	tensor_data = tensor_data1.to('cuda')

print(f'tensor type : {type(tensor_data)}, tensor shape : {tensor_data.shape}')
print(f'tensor dtype : {tensor_data.dtype}, tensor device : {tensor_data.device}')

tensor type : <class 'torch.Tensor'>, tensor shape : torch.Size([3])
tensor dtype : torch.float32, tensor device : cuda:0


In [5]:
basic_data = [ [0, 2, 4], [6, 8, 10] ]
tensor_data1 = torch.Tensor(basic_data)

if torch.cuda.is_available():
	tensor_data = tensor_data1.to('cuda')
	
print(tensor_data)

print(f'tensor type : {type(tensor_data)}, tensor shape : {tensor_data.shape}')
print(f'tensor dtype : {tensor_data.dtype}, tensor device : {tensor_data.device}')

tensor([[ 0.,  2.,  4.],
        [ 6.,  8., 10.]], device='cuda:0')
tensor type : <class 'torch.Tensor'>, tensor shape : torch.Size([2, 3])
tensor dtype : torch.float32, tensor device : cuda:0


In [6]:
np_data = np.array(basic_data)

print(np_data)

tensor_data2 = torch.from_numpy(np_data) # 기본은 float()

print(tensor_data2)
print(f'tensor dtype : {tensor_data2.dtype}, tensor device : {tensor_data2.device}')

[[ 0  2  4]
 [ 6  8 10]]
tensor([[ 0,  2,  4],
        [ 6,  8, 10]], dtype=torch.int32)
tensor dtype : torch.int32, tensor device : cpu


#### 텐서 연습

In [7]:
mat1 = torch.FloatTensor([[1,2], [3,4]])
mat2 = torch.IntTensor([[1,2], [3,4]])

In [8]:
print(mat1.shape)
print(mat2.shape)

torch.Size([2, 2])
torch.Size([2, 2])


In [9]:
print(mat1.type())
print(mat2.type())

torch.FloatTensor
torch.IntTensor


In [10]:
mat1 = torch.FloatTensor([[1,2], [3,4]])
mat2 = torch.FloatTensor([[1], [2]])

mat1 = mat1.to('cuda')
mat2 = mat2.to('cuda')

In [11]:
mat1.matmul(mat2)

tensor([[ 5.],
        [11.]], device='cuda:0')

In [12]:
mat1 * mat2

tensor([[1., 2.],
        [6., 8.]], device='cuda:0')

In [13]:
mat1.mul(mat2)

tensor([[1., 2.],
        [6., 8.]], device='cuda:0')

<img src="https://camo.githubusercontent.com/e76d463dd069d496943ecd10a3d8970237f7cf8b431fb5fd797f50b66bb01a8f/68747470733a2f2f77696b69646f63732e6e65742f696d616765732f706167652f35323834362f6e6577696d6167652e706e67" Width="700">

#### 기본 사용법 다시

##### 텐서 생성

In [15]:
## 0에서 1사이의 랜덤숫자 생성
torch.rand(2, 3)

tensor([[0.5389, 0.4542, 0.8759],
        [0.3275, 0.4472, 0.9417]])

In [16]:
## 0에서 1사이의 정규분포로 샘플링한 랜덤숫자 생성
torch.randn(2, 3)

tensor([[-0.3429,  0.8886,  0.1039],
        [-1.0649, -0.4265,  1.0233]])

In [17]:
## 시작수와 종료수 사이의 랜덤숫자 생성
torch.randint(0, 9, size=(2, 3))

tensor([[4, 1, 7],
        [1, 2, 7]])

##### 초기화

In [18]:
## 0 초기화 텐서
torch.zeros(2,3)

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [19]:
## 1초기화 텐서
torch.ones(2, 3)

tensor([[1., 1., 1.],
        [1., 1., 1.]])

In [20]:
## 0 초기화 방법2
ref = torch.rand(4, 5)
torch.zeros_like(ref)

tensor([[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]])

In [21]:
## 1 초기화 방법2
torch.ones_like(ref)

tensor([[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]])

##### 텐서 데이터타입

In [25]:
## 데이터타입 확인법 / FloatTensor(기본)
ref.type()

'torch.FloatTensor'

In [26]:
## DoubleTensor
x = torch.rand(2, 3)
x_d = x.type(dtype = torch.DoubleTensor)
x_d.type()

'torch.DoubleTensor'

In [27]:
## IntTensor
x.type_as(torch.IntTensor()).type()

'torch.IntTensor'

##### Numpy를 Tensor로