### Pytorch 설치 확인

#### Pytorch GPU
- NVIDIA 기본 확인
```shell
> nvidia-smi
...
> nvcc --version
...
```

- CUDA 설치 후
```shell
> pip install torch torchvision torchaudio --index-url https://download.pytorch.org/whl/cu121 
```

#### 기본 설치확인

In [1]:
!nvcc --version

nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2023 NVIDIA Corporation
Built on Wed_Feb__8_05:53:42_Coordinated_Universal_Time_2023
Cuda compilation tools, release 12.1, V12.1.66
Build cuda_12.1.r12.1/compiler.32415258_0


In [1]:
import torch

In [3]:
torch.__version__

'2.0.1+cu118'

In [4]:
x = torch.rand(2, 3)

In [5]:
x

tensor([[0.9848, 0.6844, 0.5573],
        [0.7097, 0.8029, 0.6083]])

#### 추가 설치확인

In [6]:
torch.cuda.is_available()

True

In [7]:
torch.cuda.get_device_name(0)

'NVIDIA GeForce GTX 1650 with Max-Q Design'

In [8]:
torch.cuda.current_device()

0

In [9]:
torch.cuda.device_count()

1

In [10]:
torch.cuda.device(0)

##### CPU Tensor

In [12]:
tensor_c = torch.zeros(3, 4)
tensor_c

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

##### GPU Tensor

In [13]:
tensor_g = tensor_c.to('cuda')
tensor_g

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]], device='cuda:0')

##### 다시 CPU Tensor로

In [8]:
tensor_b = tensor_g.to('cpu')
tensor_b

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

### NLTK/KoNLPy 설치
- 자연어/한국어 자연어 처리 패키지

#### NLTK 설치
- NLTK 설치
```shell
> pip install nltk
```

In [10]:
!pip install nltk

  Using cached joblib-1.4.2-py3-none-any.whl.metadata (5.4 kB)
     ---------------------------------------- 0.0/42.0 kB ? eta -:--:--
     -------------------------------------- 42.0/42.0 kB 991.7 kB/s eta 0:00:00
     ---------------------------------------- 0.0/57.6 kB ? eta -:--:--
     ---------------------------------------- 57.6/57.6 kB ? eta 0:00:00
   ---------------------------------------- 0.0/1.5 MB ? eta -:--:--
   ------------------------ --------------- 0.9/1.5 MB 29.4 MB/s eta 0:00:01
   ---------------------------------------- 1.5/1.5 MB 19.2 MB/s eta 0:00:00
   ---------------------------------------- 0.0/269.0 kB ? eta -:--:--
   ---------------------------------------- 269.0/269.0 kB 8.3 MB/s eta 0:00:00
   ---------------------------------------- 0.0/97.9 kB ? eta -:--:--
   ---------------------------------------- 97.9/97.9 kB 5.8 MB/s eta 0:00:00
Using cached joblib-1.4.2-py3-none-any.whl (301 kB)
   ---------------------------------------- 0.0/78.3 kB ? eta -:--

In [11]:
import nltk

In [12]:
nltk.__version__

'3.8.1'

#### NLTK Data 다운로드

In [13]:
nltk.download()

showing info https://raw.githubusercontent.com/nltk/nltk_data/gh-pages/index.xml


True

<img src="https://raw.githubusercontent.com/hugoMGSung/study-pytorch/main/images/torch0002.png" width="600">

#### KoNLPy 설치
- KoNLPy 설치
```shell
> pip install konlpy
```

- 에러발생 시는 JDK 설치

In [14]:
!pip install konlpy

   ---------------------------------------- 0.0/19.4 MB ? eta -:--:--
    --------------------------------------- 0.4/19.4 MB 11.6 MB/s eta 0:00:02
   --- ------------------------------------ 1.8/19.4 MB 27.8 MB/s eta 0:00:01
   ------- -------------------------------- 3.8/19.4 MB 30.1 MB/s eta 0:00:01
   ------------ --------------------------- 6.1/19.4 MB 38.9 MB/s eta 0:00:01
   ------------------ --------------------- 8.8/19.4 MB 40.1 MB/s eta 0:00:01
   ------------------------ --------------- 11.8/19.4 MB 54.7 MB/s eta 0:00:01
   ----------------------------- ---------- 14.5/19.4 MB 59.5 MB/s eta 0:00:01
   ------------------------------------ --- 17.6/19.4 MB 59.5 MB/s eta 0:00:01
   ---------------------------------------  19.4/19.4 MB 59.5 MB/s eta 0:00:01
   ---------------------------------------- 19.4/19.4 MB 46.7 MB/s eta 0:00:00
   ---------------------------------------- 0.0/351.5 kB ? eta -:--:--
   --------------------------------------- 351.5/351.5 kB 21.3 MB/s eta 0:

In [15]:
import konlpy
konlpy.__version__

'0.6.0'

#### JPype 설치
- JAVA와 Python 연결 패키지. 현재 기준이 Python 3.10이므로...
- https://github.com/jpype-project/jpype/releases 에서 확인

```shell
> pip install JPype1-1.5.0-cp310-cp310-win_amd64.whl 
```