### 텐서 기본

In [1]:
import torch

In [3]:
x = torch.tensor([[1,2,3], [4,5,6], [7,8,9]])
print(x)
print("Size:", x.size())
print("Shape:", x.shape)
print("Rank(Dimension):", x.ndimension())

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])
Size: torch.Size([3, 3])
Shape: torch.Size([3, 3])
Rank(Dimension): 2


In [7]:
# 랭크(차원) 늘리기
x = torch.unsqueeze(x, 0)
print(x)
print("Size:", x.size())
print("Shape:", x.shape)
print("Rank(Dimension):", x.ndimension())

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])
Size: torch.Size([1, 3, 3])
Shape: torch.Size([1, 3, 3])
Rank(Dimension): 3


In [8]:
# 랭크 줄이기
x = torch.squeeze(x)
print(x)
print("Size:", x.size())
print("Shape:", x.shape) #[3, 3] 2개의 차원에 각 3개의 원소를 가진 텐서
print("Rank(Dimension):", x.ndimension())

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])
Size: torch.Size([3, 3])
Shape: torch.Size([3, 3])
Rank(Dimension): 2


In [9]:
# 랭크의 형태 바꾸기
x = x.view(9)
print(x)
print("Size:", x.size())
print("Shape:", x.shape)
print("Rank(Dimension):", x.ndimension())

tensor([1, 2, 3, 4, 5, 6, 7, 8, 9])
Size: torch.Size([9])
Shape: torch.Size([9])
Rank(Dimension): 1


In [14]:
try:
    x = x.view(2,4)
    print(x)
except Exception as e:
    print(e) #에러 출력

shape '[2, 4]' is invalid for input of size 9


In [15]:
try:
    x = x.view(3,3)
    print(x)
except Exception as e:
    print(e) #에러 출력

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])


#### 연산과 행렬곱

In [16]:
w = torch.randn(5,3, dtype=torch.float)
x = torch.tensor([[1.0,2.0], [3.0,4.0], [5.0,6.0]])
print("w size:", w.size())
print("x size:", x.size())
print("w:", w)
print("x:", x)

w size: torch.Size([5, 3])
x size: torch.Size([3, 2])
w: tensor([[-0.0407,  0.0852,  0.3237],
        [ 1.1919,  0.4505,  2.4119],
        [ 0.3384, -0.1425, -2.0910],
        [ 0.1089, -0.6897,  1.5481],
        [-0.7361, -1.0800,  1.0334]])
x: tensor([[1., 2.],
        [3., 4.],
        [5., 6.]])


In [18]:
b = torch.randn(5,2, dtype=torch.float)
print("b:", b.size())
print("b:", b)

b: torch.Size([5, 2])
b: tensor([[-1.0902,  2.0504],
        [-0.7136, -0.7415],
        [ 0.6327, -0.3788],
        [-0.4368, -1.3595],
        [ 1.0969, -0.3333]])


In [19]:
wx = torch.mm(w,x) # w의 행은 5, x의 열은 2, 즉 shape는 [5, 2]입니다.
print("wx size:", wx.size())
print("wx:", wx)


wx size: torch.Size([5, 2])
wx: tensor([[  1.8332,   2.2013],
        [ 14.6029,  18.6571],
        [-10.5440, -12.4392],
        [  5.7803,   6.7476],
        [  1.1908,   0.4081]])


In [20]:
result = wx + b	
print("result size:", result.size()) 
print("result:", result) 

result size: torch.Size([5, 2])
result: tensor([[  0.7430,   4.2517],
        [ 13.8892,  17.9156],
        [ -9.9113, -12.8180],
        [  5.3434,   5.3881],
        [  2.2877,   0.0748]])


#### 미분

In [27]:
w = torch.tensor(1.0, requires_grad=True)

a = w*3
l = a**2

l.backward()

print('l을 w로 미분한 값은 {}'.format(w.grad))

l을 w로 미분한 값은 18.0


In [25]:
# 1. 텐서 정의 및 requires_grad=True 설정. 해당 텐서에 대해 미분 값을 추적하겠음
x = torch.tensor(2.0, requires_grad=True)  # x는 미분 계산에 포함됨
y = torch.tensor(3.0, requires_grad=True)  # y도 포함

# 2. 계산 그래프 생성
z = x ** 2 + y ** 3  # z = x^2 + y^3

# 3. z를 기준으로 미분 수행 (backpropagation)
z.backward()

# 4. 결과 출력. 미분결과는 각 텐서의 .grad 속성에 저장
print(f"x에 대한 미분 (dz/dx): {x.grad}")  # dz/dx = 2*x = 4
print(f"y에 대한 미분 (dz/dy): {y.grad}")  # dz/dy = 3*y^2 = 27

x에 대한 미분 (dz/dx): 4.0
y에 대한 미분 (dz/dy): 27.0
